# fly.toml file generated for empty-field-4404 on 2023-02-07T11:18:42+02:00

app = "empty-field-4404"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8085"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443



[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"