---
name: periodic health check

on:
  schedule:
    - cron: '30 5 * * 2'

jobs:
  test_schedule:
    runs-on: ubuntu-20.04
    steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v3
      with:
        url: https://empty-field-4404.fly.dev/
...